### ISSUE TITLE
Long suggestion list does not scroll with highlighted entry. 

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/ep_autocomp#18]
**What I did:** I wanted to autocomplete a word with had a long list of possible suggestions for an input (>10 suggestions). I wanted to select one at the end of the list.

**What I expected:** When I selected the bottom most entry of the entries currently shown in the scrollable list, I expected the list to scroll down as I select the next entry below

**What happened:** The highlighted/selected entry was shifted to the next item, but it was not visible since the list did not scroll with the selection.

![this is o.k.](http://i.imgur.com/xfmyMnN.png)
one more…

![this is not, as it is not visible](http://i.imgur.com/u0fFE06.png)
oops. That small blueish line on the bottom is the barely visible next list entry.

Apologies for overly meaningless testing content *a,aa,aaa…*

**Comment by lpagliari** [comment]
@jdittrich which browser did you test? @joassouza mentioned he tested on Chrome and it was working as expected.

**Comment by jdittrich** [comment]
firefox, most current stable on linux

**Comment by joassouza** [comment]
Hey @jdittrich, maybe I missed some detail. I tested in the firefox 42 on fedora 22 and it seems ok.
Is that the version you're using?
I could select the last option typing arrow down. 
![screenshot from 2015-11-17 16-15-12](https://cloud.githubusercontent.com/assets/4945372/11222035/fb3c2e34-8d46-11e5-8d3b-c21074c416c9.jpeg)

**Comment by jdittrich** [comment]
My fault. The most current one works, the one from a week ago (or so) had the problem. Thanks for helping me to sort out this… Sorry.
