### ISSUE TITLE
ease configuration

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/ep_autocomp#2]
**What should be possible:**
configuring the autocompletion by editing a simple JSON or CSV file where the desired autocompletion style can be set. 
The desired state should than be loaded from autocompletion-styles that are delivered with the plugin.  

**How it is now**: a config-object in the code needs to be edited.

**Comment by JohnMcLear** [comment]
I have funding for this for me to do it..  Or if you want to do it I can fund you to do it ??? :)

**Comment by JohnMcLear** [comment]
Only took a few hours so I did it

**Comment by jdittrich** [comment]
thanks!

**Comment by JohnMcLear** [comment]
Please close
