### ISSUE TITLE
Default value to enable "autocomp" in settings.json

### ISSUE THREAD

**Issue by Wikinaut** [jdittrich/ep_autocomp#26]
Is there a clean way to enable the autocompletion in the main settings.json, so that all users have the setting already enabled in their pads ?

**Comment by lpagliari** [comment]
No, @Wikinaut . For now you can use a parameter on the URL `?autocomp=true` to enable autocomp, but config via `settings.json` was not implemented yet.

**Comment by Wikinaut** [comment]
Thanks. Such a setting would be a ```nice to have```.

**Comment by lpagliari** [comment]
So let's leave this opened and marked as enhancement. :-)

**Comment by JohnMcLear** [comment]
Done in https://github.com/jdittrich/ep_autocomp/pull/27

**Comment by JohnMcLear** [comment]
@Wikinaut please close
