### ISSUE TITLE
Autocomp suggestions not working

### ISSUE THREAD

**Issue by kernelfreak** [jdittrich/ep_autocomp#33]
Hello,

How to exactly enable autocomp for Etherpad? I already called npm install ep_autocomp when I am in etherpad-lite folder. When I navigate to etherpad-lite/node_modules/, I see a folder ep_autocomp in it. THen I restarted etherpad, but I don't see word suggestions, even with the text just typed. What am I missing? The documentation just mentioned to 'Enable under settings', I cannot find anything related to autocompletion in settings.json. Thank you.

**Comment by jdittrich** [comment]
Did you try to click on 

![image](https://cloud.githubusercontent.com/assets/3416487/21389709/4c94a0dc-c783-11e6-9d40-1028cfdde4e7.png)

and enable it there?

**Comment by joassouza** [comment]
Hey, you've to add the config on the setting.json.
https://github.com/jdittrich/ep_autocomp/blob/master/README.md#advanced-customization

**Comment by kernelfreak** [comment]
@jdittrich : Where is the gear icon you have shown? Thank you.

**Comment by kernelfreak** [comment]
@joassouza After adding the the ep_autocomp mentioned in advanced customization in etherpad-lite/settings.json, I get the following error : [2016-12-21 13:52:51.879] [ERROR] console - There was an error processing your settings.json file: Unexpected string

**Comment by kernelfreak** [comment]
My bad, was missing a comma.
