### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Billaboong** [jdittrich/ep_autocomp#34]
Hi
Does this plugin suggest words typed as the text highlighted in green and the words be not in the pad?

Original sentence: I think this the way to go.We don't have all the time in the world to test this.

New sentence: I think this the way to go.We don't have forever and ever to test this.

![etherpad-lite-autocomplete](https://user-images.githubusercontent.com/4427236/28814296-af9ecfd2-76a5-11e7-9bd2-d879fe9603c7.png)

**Comment by jdittrich** [comment]
The words that the plugin suggests can only be words that are already in the text. So it will *not* suggest "forever" when you type "all the time". If you have written "fore" it will suggest "forever" if, and only if, the word "forever" already can be found in the document. 

[Language Tool](https://languagetool.org/) does style-based suggestions, like suggesting  "forever" when you type "all the time". But language tool is currently not integrated in Etherpad and making this integration is not in the scope of *ep_autocomp*

**Comment by Billaboong** [comment]
@jdittrich Thanks alot for that insight.
