### ISSUE TITLE
Use ESC to close suggestions

### ISSUE THREAD

**Issue by lpagliari** [jdittrich/ep_autocomp#4]
I've seen that Ctrl+space closes the suggestions box. Was there any reason to not use ESC as shortcut to close suggestions box? Any concerns or risks?

**Comment by jdittrich** [comment]
I don’t think so. Best guess (it’s bee a while): I did not think of it, tough it seems like a good idea. (unlikely tech-case against it: Esc gets caught by some other thing)

**Comment by jdittrich** [comment]
If you use the plug in, I can have a look on how the implement it; just in case you are on it, I’d gladly take a pull request.

**Comment by lpagliari** [comment]
Sweet! @joassouza and I are starting to work on ep_autocomp, so you'll probably see some PRs soon. Using ESC to close suggestions box is one of the things we thought would be useful, but there are some others too.

One more question: was there any reason for you to choose to create a folder `ep_autocomp/ep_autocomp/`? What I usually see on plugins is to have the files directly on `ep_autocomp/` -- and to be honest when I tried to git-clone and start using ep_autocomp I could not start Etherpad before extracting the inner folder to `node_modules/` directly. I'm wondering if I'm doing something wrong when installing the plugin...

**Comment by jdittrich** [comment]
> One more question: was there any reason for you to choose to 
> create a folder ep_autocomp/ep_autocomp/

Pretty sure, no. Again, feel free to "lift" it up. Just a stupid mistake by me. 

btw.: glad that you are using/working on it. Its actually a neat function imho, but I had no particular usecase recently for myself, though it could be great for pair coding or whatever.

**Comment by lpagliari** [comment]
Great! See #5 for some improvements. We'll start working on some other issues/new features now, hope they are useful.

BTW, congrats for the plugin, it looks very good and surely will be useful for us.
